import { z } from 'zod';

export const AddBookSchema = z.object({
  isbn: z.string().optional(),
  quote: z.string().optional(),
  image: z.string().optional(),
  summary: z.string().optional(),
  language: z.string().optional(),
  translator: z.string().optional(),
  illustrator: z.string().optional(),
  volume: z.number().int().optional(),
  printing: z.number().int().optional(),
  completed: z.boolean().default(false),
  endDate: z.string().datetime().optional(),
  startDate: z.string().datetime().optional(),
  rating: z.number().min(1).max(5).default(5),
  acquiredDate: z.string().datetime().optional(),
  name: z.string().min(1, 'Book title is required'),
  publicationDate: z.string().datetime().optional(),
  category: z.string().min(1, 'Category is required'),
  publisher: z.string().min(1, 'Publisher is required'),
  author: z.string().min(1, "Author's name is required"),
  type: z.enum(['BOOK', 'EBOOK', 'AUDIO_BOOK']).default('BOOK'),
  pageCount: z.number().int().min(1, 'Page count is required'),
  genre: z.array(z.string()).min(1, 'At least one genre is required'),
});
